nginx:
  build: ./balanceador/
  container_name: balanceador
  volumes:
    - /var/log/mniws:/var/log/hostlogs
  ports:
    - "80:80"
  links:
    - saelgi
#  restart: always

saelgi:
  image: saelgi:1.0.0
  container_name: mniws
  env_file: mniws.properties
  volumes:
    - /var/log/saelgi/saelgi:/log/saelgi
#  restart: always