server:
  contextPath: /saelgi
  port: 8080

security:
  user:
    name: luiz.hartke
    password: lego123
    
logging:
  level:
    org.springframework.security: DEBUG

spring:
  datasource:
    platform: hsqldb
